name: Create requirements file based on the python program

on:
  push:
  
jobs:
  read-from-file:
    runs-on: ubuntu-latest
    steps:
      - name: "Test pip"
        run: pipreqs --version | jq
        shell: bash

