name: Create requirements file based on the python program

on:
  pull_request:
  
jobs:
  read-from-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Test pip"
        run: pipreqs --version
        shell: bash

